### ISSUE TITLE
If the channel has moved from offline to online, an error occurs.

### ISSUE THREAD

**Issue by EnterGin** [Instinctlol/automatic-twitch-recorder#12]
The main function of the script does not work. If the channel was offline, and then switched to online, the recording does not go. You can only record after restarting the cmd. Python 3.7.3, Windows 7 Ultimate x64.
![1](https://user-images.githubusercontent.com/51099894/58442052-07084680-80f0-11e9-9ddb-a5d9298296ee.jpg)

**Comment by Lawrence575** [comment]
I was able to fix it without basically any knowledge on how to code.

**Comment by EnterGin** [comment]
Ahahahahaha. I have already fixed this for a long time, thanks for answer.

**Comment by Lawrence575** [comment]
ah okay lol. Here I was trying to figure out how to set up a repository so I can fork it over to you.

**Comment by Lawrence575** [comment]
I just used call scripts to call forth the scripts for different streamers because I have multiple people on watch, didn't figure out how to automate multiple people with one script so I bit the bullet and kept it as is with the changes.

**Comment by EnterGin** [comment]
If you have your solution, it would be nice to share it with people, so go ahead.

**Comment by Lawrence575** [comment]
i got 0 clue how to import mine to it tho. I'm using the browser. and its a bit of an older version i guess from when he last updated it: 
[Twitch.tv Recorder.zip](https://github.com/Instinctlol/automatic-twitch-recorder/files/3412315/Twitch.tv.Recorder.zip) best i can do is upload it here lol

**Comment by EnterGin** [comment]
Thanks btw!
