### ISSUE TITLE
Stream filename errors

### ISSUE THREAD

**Issue by FirestrikeX** [Instinctlol/automatic-twitch-recorder#14]
The method you're calling to get a valid filename `get_valid_filename` from utils under watcher.py does not remove back slashes and forward slashes from stream titles leading to an error in writing the file

`file_name = curr_time + " - " + self.streamer + " - " + get_valid_filename(self.stream_title) + ".flv"`

**Comment by Instinctlol** [comment]
Thank you. I'm changing to the better suited [sanitize_filename](https://pypi.org/project/pathvalidate/#sanitize-a-filename). I didn't know this function existed.

Duplicate of #13
