### ISSUE TITLE
Integrate cmd library

### ISSUE THREAD

**Issue by Instinctlol** [Instinctlol/automatic-twitch-recorder#8]
Integrating the [cmd library](https://pymotw.com/2/cmd/) is the first step to support the idea of recording multiple streams. With this library, one is able to launch multiple commands.

It should also work well with the getopts library.

At a later step, my idea is to launch 'check' commands via cmd, these will then be checked in certain time intervals by a checker singleton. If the singleton finds the stream to be recordable, it will launch a watcher, which will record the stream and notify the singleton on completion, so that it can be checked again.

Another good thing about having this checker singleton is that we will be able to easily implement a ui on top of that.

**Comment by maxb2** [comment]
I made an object-oriented version of the script on the branch [objectify](Instinctlol/automatic-twitch-recorder/tree/objectify). Treating the streams as objects should make handling multiple streams a lot easier.

**Comment by Instinctlol** [comment]
https://github.com/Instinctlol/automatic-twitch-recorder/commit/dc9496342f836e052ed6b23d635ceb509e6e6ebf resolves this.
